[toolchain]
anchor_version = "0.30.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
signer_check = "6PpTEM9LKNPCSUHgwqxdXK6nmSuMwTkh8k81D56SFVhf"
pda_sharing = "ECg8PSWDnt1bxBxoQrmp7T2eUTSfo7aYecAiamSRdACg"
reinitialization = "FhtVsPAxuvMJhgsMMnegK9Qv4dTwxn6JdKwPypWSMYag"
integer_overflow = "GfN9UbCqhCwPQzpZL8aVqDSwaFpDGZ9SdRii9YvJaoVZ"
pinocchio_vs_anchor = "rZP3GCrKbBRrVgA4t14HEve5s1VCXfye1NahKuBUps2"
account_closing = "ACmY1XMJy94VkriJN6o77UjDr1qRWBYe67JrMagY2Gto"
bump_seed_canonicalization = "Bumj5wt9dm2cK2o9ayeguHUtpnwnUFLQHaqUaewFegV2"
owner_checks = "owjTGQ5tcsF9jiy1rDeiBxKj7fAcz3h8tbs9q9f5Awm"
type_cosplay = "Ty2F8Q6C9m695p29DS6gMziMhGBhr4KPh7RkCp4p21a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
