[toolchain]
anchor_version = "0.30.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
signer_check = "6PpTEM9LKNPCSUHgwqxdXK6nmSuMwTkh8k81D56SFVhf"
pda_sharing = "ECg8PSWDnt1bxBxoQrmp7T2eUTSfo7aYecAiamSRdACg"
reinitialization = "FhtVsPAxuvMJhgsMMnegK9Qv4dTwxn6JdKwPypWSMYag"
integer_overflow = "GfN9UbCqhCwPQzpZL8aVqDSwaFpDGZ9SdRii9YvJaoVZ"
pinocchio_vs_anchor = "rZP3GCrKbBRrVgA4t14HEve5s1VCXfye1NahKuBUps2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
