[workspace]
resolver = "2"
members = [
    "programs/signer_check",
    "programs/pda_sharing",
    "programs/reinitialization",
    "programs/integer_overflow",
    "programs/pinocchio_vs_anchor"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
